/**
* Generated by pojo-mapping ${pluginVersion!}
*/
Ext.define('change.me.${modelClsName}', {
    extend: 'Ext.data.Model',
    <#if idField??>
    idProperty: '${idField}',
    </#if>
    fields: [
        <#list fieldItems as fieldItem>
        {name: '${fieldItem.name}'}<#if fieldItem_has_next>,</#if>
        </#list>
    ]
});